// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: api/grpc/go-session.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoSessionClient is the client API for GoSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoSessionClient interface {
	ServiceMethod(ctx context.Context, in *ServiceMethodRequest, opts ...grpc.CallOption) (*ServiceMethodResponse, error)
}

type goSessionClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSessionClient(cc grpc.ClientConnInterface) GoSessionClient {
	return &goSessionClient{cc}
}

func (c *goSessionClient) ServiceMethod(ctx context.Context, in *ServiceMethodRequest, opts ...grpc.CallOption) (*ServiceMethodResponse, error) {
	out := new(ServiceMethodResponse)
	err := c.cc.Invoke(ctx, "/go.session.GoSession/ServiceMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSessionServer is the server API for GoSession service.
// All implementations must embed UnimplementedGoSessionServer
// for forward compatibility
type GoSessionServer interface {
	ServiceMethod(context.Context, *ServiceMethodRequest) (*ServiceMethodResponse, error)
	mustEmbedUnimplementedGoSessionServer()
}

// UnimplementedGoSessionServer must be embedded to have forward compatible implementations.
type UnimplementedGoSessionServer struct {
}

func (UnimplementedGoSessionServer) ServiceMethod(context.Context, *ServiceMethodRequest) (*ServiceMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceMethod not implemented")
}
func (UnimplementedGoSessionServer) mustEmbedUnimplementedGoSessionServer() {}

// UnsafeGoSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoSessionServer will
// result in compilation errors.
type UnsafeGoSessionServer interface {
	mustEmbedUnimplementedGoSessionServer()
}

func RegisterGoSessionServer(s grpc.ServiceRegistrar, srv GoSessionServer) {
	s.RegisterService(&GoSession_ServiceDesc, srv)
}

func _GoSession_ServiceMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSessionServer).ServiceMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.session.GoSession/ServiceMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSessionServer).ServiceMethod(ctx, req.(*ServiceMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoSession_ServiceDesc is the grpc.ServiceDesc for GoSession service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoSession_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.session.GoSession",
	HandlerType: (*GoSessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceMethod",
			Handler:    _GoSession_ServiceMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/go-session.proto",
}
